#include "defs.h"

int VAL[] = {P_VAL, N_VAL, B_VAL, R_VAL, Q_VAL, K_VAL, -P_VAL, -N_VAL, -B_VAL, -R_VAL, -Q_VAL, -K_VAL, 0, 0, 0, 0};
int ISBLACK[] = {0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1};
int COLOR[] = {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, WHITE, BLACK, OCCUPIED, EMPTY};
